apiVersion: v1
kind: Service
metadata:
  name: asterdrive-headless
  labels:
    app.kubernetes.io/name: asterdrive
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: asterdrive
  ports:
    - name: http
      appProtocol: http
      port: 3000
      targetPort: http
