use serde::{Deserialize, Serialize};
#[cfg(all(debug_assertions, feature = "openapi"))]
use utoipa::ToSchema;

use std::collections::BTreeMap;
use std::sync::Arc;

use crate::storage::drivers::onedrive::MicrosoftGraphAccessTokenProvider;
use aster_drive_model::types::{
    RemoteNodeTransportMode, StorageCredentialKind, StorageCredentialProvider,
};
use aster_drive_storage::{
    ConnectorConfigEnvelope, StoragePolicyBehaviorConfig, StoragePolicyExecutableAction,
};

/// Exactly one connector credential channel supplied by an API caller.
///
/// The tagged representation makes static credentials and authorization
/// application credentials structurally mutually exclusive. Each connector
/// deserializes `values` into the typed credential struct generated by its
/// schema declaration.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(tag = "mode", content = "values", rename_all = "snake_case")]
#[cfg_attr(all(debug_assertions, feature = "openapi"), derive(ToSchema))]
pub enum StorageConnectorCredentialInput {
    #[default]
    None,
    Static(serde_json::Value),
    AuthorizationApplication(serde_json::Value),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
#[cfg_attr(all(debug_assertions, feature = "openapi"), derive(ToSchema))]
pub struct StorageConnectorConnectionInput {
    #[cfg_attr(all(debug_assertions, feature = "openapi"), schema(value_type = Object))]
    pub connector_config: ConnectorConfigEnvelope<BTreeMap<String, serde_json::Value>>,
    pub behavior: StoragePolicyBehaviorConfig,
    pub credential: StorageConnectorCredentialInput,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct StorageConnectorCredentialRequirement {
    pub provider: StorageCredentialProvider,
    pub credential_kind: StorageCredentialKind,
    pub requires_application_config: bool,
    pub requires_authorization: bool,
}

/// Strongly typed legacy credential rows used only by AsterDrive 0.5.0.
///
/// The deprecated table models stay outside the normal entity namespace. Core
/// migration code loads them, while each connector owns conversion into its
/// current credential payload. This type and the legacy tables will be
/// completely removed in AsterDrive 0.6.0.
#[derive(Clone, Debug, Default)]
pub(crate) struct LegacyStorageConnectorCredentialInput {
    pub static_credential: Option<LegacyStoragePolicyStaticCredential>,
    #[allow(deprecated)]
    pub application_config:
        Option<aster_drive_model::deprecated::storage_connector_application_config::Model>,
    #[allow(deprecated)]
    pub authorization: Option<aster_drive_model::deprecated::storage_policy_credential::Model>,
}

impl LegacyStorageConnectorCredentialInput {
    pub(crate) fn is_empty(&self) -> bool {
        self.static_credential.is_none()
            && self.application_config.is_none()
            && self.authorization.is_none()
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct LegacyStoragePolicyStaticCredential {
    pub access_key: String,
    pub secret_key: String,
}

#[derive(Clone)]
pub(crate) struct OneDriveCredentialRuntime {
    pub token_provider: Arc<dyn MicrosoftGraphAccessTokenProvider>,
    pub drive_id: Option<String>,
    pub root_item_id: Option<String>,
}

#[derive(Clone)]
pub(crate) enum StorageConnectorRuntimeCredential {
    Static(serde_json::Value),
    MicrosoftGraph(OneDriveCredentialRuntime),
}

/// Minimal local-filesystem behavior exposed to product workflows.
///
/// The concrete local connector owns its persisted schema. Callers receive
/// only the runtime facts needed for staging and content deduplication.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct LocalFilesystemPolicyProjection {
    pub base_path: String,
    pub content_dedup: bool,
}

/// Connector-owned remote binding facts used by routing and topology checks.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct RemotePolicyBindingProjection {
    pub remote_node_id: Option<i64>,
    pub download_strategy: aster_drive_model::types::RemoteDownloadStrategy,
    pub upload_strategy: aster_drive_model::types::RemoteUploadStrategy,
}

#[derive(Debug, Clone)]
pub(crate) struct StorageCredentialValidationOutcome {
    pub credential_payload: serde_json::Value,
    pub account_label: Option<String>,
    pub subject: Option<String>,
    pub metadata: String,
    pub root_item_id: String,
    pub root_item_name: Option<String>,
}

#[derive(Clone, Debug, Serialize)]
#[cfg_attr(all(debug_assertions, feature = "openapi"), derive(ToSchema))]
pub struct StorageConnectorCredentialInfo {
    pub id: i64,
    pub policy_id: i64,
    pub provider: StorageCredentialProvider,
    pub credential_kind: StorageCredentialKind,
    pub account_label: Option<String>,
    pub subject: Option<String>,
    pub tenant_id: Option<String>,
    pub scopes: Vec<String>,
    pub status: aster_drive_model::types::StorageCredentialStatus,
    pub status_reason: Option<String>,
    #[cfg_attr(all(debug_assertions, feature = "openapi"), schema(value_type = Option<String>))]
    pub expires_at: Option<chrono::DateTime<chrono::Utc>>,
    #[cfg_attr(all(debug_assertions, feature = "openapi"), schema(value_type = Option<String>))]
    pub authorized_at: Option<chrono::DateTime<chrono::Utc>>,
    #[cfg_attr(all(debug_assertions, feature = "openapi"), schema(value_type = Option<String>))]
    pub last_refreshed_at: Option<chrono::DateTime<chrono::Utc>>,
    #[cfg_attr(all(debug_assertions, feature = "openapi"), schema(value_type = Option<String>))]
    pub last_validated_at: Option<chrono::DateTime<chrono::Utc>>,
    #[cfg_attr(all(debug_assertions, feature = "openapi"), schema(value_type = String))]
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[cfg_attr(all(debug_assertions, feature = "openapi"), schema(value_type = String))]
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone)]
pub struct ExecuteSavedStorageConnectorActionInput {
    pub action: StoragePolicyExecutableAction,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
#[cfg_attr(all(debug_assertions, feature = "openapi"), derive(ToSchema))]
pub struct ExecuteDraftStorageConnectorActionInput {
    pub action: StoragePolicyExecutableAction,
    pub policy_id: Option<i64>,
    pub connection: StorageConnectorConnectionInput,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
#[cfg_attr(all(debug_assertions, feature = "openapi"), derive(ToSchema))]
pub struct TestDraftStorageConnectorConnectionInput {
    pub policy_id: Option<i64>,
    pub connection: StorageConnectorConnectionInput,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(all(debug_assertions, feature = "openapi"), derive(ToSchema))]
pub struct TencentCosCorsConfigResult {
    pub rule_id: String,
    pub allowed_origins: Vec<String>,
    pub request_id: Option<String>,
    pub preserved_rule_count: usize,
    pub replaced_existing_rule: bool,
    pub response_vary: bool,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(all(debug_assertions, feature = "openapi"), derive(ToSchema))]
pub struct StorageConnectorActionResult {
    pub action: StoragePolicyExecutableAction,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tencent_cos_cors: Option<TencentCosCorsConfigResult>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct StoragePolicyCleanupRemoteNodeSnapshot {
    pub id: i64,
    pub name: String,
    pub base_url: String,
    #[serde(default)]
    pub transport_mode: RemoteNodeTransportMode,
    pub access_key_ciphertext: String,
    pub secret_key_ciphertext: String,
    #[serde(default)]
    pub last_capabilities: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct StoragePolicyCleanupOneDriveCredentialSnapshot {
    pub cloud: aster_drive_model::types::MicrosoftGraphCloud,
    #[serde(default)]
    pub tenant_id: Option<String>,
    #[serde(default)]
    pub client_id: Option<String>,
    #[serde(default)]
    pub client_secret_ciphertext: Option<String>,
    pub drive_id: String,
    pub root_item_id: String,
    pub access_token_ciphertext: String,
    #[serde(default)]
    pub refresh_token_ciphertext: Option<String>,
    #[serde(default)]
    pub expires_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub(crate) enum StoragePolicyCleanupDriverSnapshot {
    RemoteNode(StoragePolicyCleanupRemoteNodeSnapshot),
    MicrosoftGraph(StoragePolicyCleanupOneDriveCredentialSnapshot),
}

#[derive(Debug, Clone, Copy)]
pub(crate) struct StoragePolicyCleanupSnapshots<'a> {
    pub driver_snapshot: Option<&'a StoragePolicyCleanupDriverSnapshot>,
}

impl From<crate::storage::drivers::tencent_cos::cors::TencentCosCorsApplyResult>
    for TencentCosCorsConfigResult
{
    fn from(value: crate::storage::drivers::tencent_cos::cors::TencentCosCorsApplyResult) -> Self {
        Self {
            rule_id: value.rule_id,
            allowed_origins: value.allowed_origins,
            request_id: value.request_id,
            preserved_rule_count: value.preserved_rule_count,
            replaced_existing_rule: value.replaced_existing_rule,
            response_vary: value.response_vary,
        }
    }
}
