[profile.default]
fail-fast = false
retries = 0

[profile.ci]
inherits = "default"
status-level = "fail"
final-status-level = "slow"

[profile.database]
inherits = "ci"
test-threads = 16
slow-timeout = { period = "120s", terminate-after = 4 }

[profile.external]
inherits = "ci"
test-threads = 1
