//! SeaORM 实体定义：`managed_follower`。

use sea_orm::Set;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use std::fmt;
#[cfg(all(debug_assertions, feature = "openapi"))]
use utoipa::ToSchema;

use crate::types::RemoteNodeTransportMode;

#[derive(Clone, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[cfg_attr(all(debug_assertions, feature = "openapi"), derive(ToSchema))]
#[sea_orm(table_name = "managed_followers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    /// Administrative display name for the remote node.
    pub name: String,
    /// Direct transport base URL; reverse-tunnel nodes keep this empty.
    pub base_url: String,
    /// Credential used to authenticate control-plane requests to the node.
    pub access_key: String,
    #[serde(skip_serializing)]
    /// Secret paired with `access_key`; never serialize or log this value.
    pub secret_key: String,
    /// Whether administrative operations and runtime transport are enabled.
    pub is_enabled: bool,
    /// Configured transport selection used to reach this remote node.
    pub transport_mode: RemoteNodeTransportMode,
    /// Capabilities returned by the most recent explicit remote-node probe.
    pub last_capabilities: String,
    /// Error from the most recent explicit remote-node probe or connection test.
    pub last_error: String,
    #[cfg_attr(all(debug_assertions, feature = "openapi"), schema(value_type = Option<String>))]
    /// Time at which `last_capabilities` and `last_error` were recorded.
    pub last_checked_at: Option<DateTimeUtc>,
    /// Transient reverse-tunnel runtime error; a successful poll or stream handshake clears it.
    pub tunnel_last_error: String,
    /// Desired binding-control revision generated by the primary.
    pub binding_revision: i64,
    /// Latest binding-control revision applied by the follower.
    pub binding_applied_revision: i64,
    #[cfg_attr(all(debug_assertions, feature = "openapi"), schema(value_type = Option<String>))]
    /// Last successful reverse-tunnel poll or stream handshake observed by this primary.
    pub tunnel_last_seen_at: Option<DateTimeUtc>,
    #[cfg_attr(all(debug_assertions, feature = "openapi"), schema(value_type = String))]
    /// Time at which the remote node record was created.
    pub created_at: DateTimeUtc,
    #[cfg_attr(all(debug_assertions, feature = "openapi"), schema(value_type = String))]
    /// Time of the latest administrative change to the remote node record.
    pub updated_at: DateTimeUtc,
}

impl fmt::Debug for Model {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Model")
            .field("id", &self.id)
            .field("name", &self.name)
            .field("base_url", &self.base_url)
            .field("access_key", &"***REDACTED***")
            .field("secret_key", &"***REDACTED***")
            .field("is_enabled", &self.is_enabled)
            .field("transport_mode", &self.transport_mode)
            .field("last_capabilities", &self.last_capabilities)
            .field("last_error", &self.last_error)
            .field("last_checked_at", &self.last_checked_at)
            .field("tunnel_last_error", &self.tunnel_last_error)
            .field("binding_revision", &self.binding_revision)
            .field("binding_applied_revision", &self.binding_applied_revision)
            .field("tunnel_last_seen_at", &self.tunnel_last_seen_at)
            .field("created_at", &self.created_at)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::follower_enrollment_session::Entity")]
    FollowerEnrollmentSessions,
}

impl Related<super::follower_enrollment_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FollowerEnrollmentSessions.def()
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if insert {
            if !self.transport_mode.is_set() {
                self.transport_mode = Set(RemoteNodeTransportMode::Direct);
            }
            if !self.tunnel_last_error.is_set() {
                self.tunnel_last_error = Set(String::new());
            }
            if !self.tunnel_last_seen_at.is_set() {
                self.tunnel_last_seen_at = Set(None);
            }
        }
        Ok(self)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn debug_redacts_managed_follower_credentials() {
        let now = chrono::Utc::now();
        let model = Model {
            id: 1,
            name: "follower".to_string(),
            base_url: "https://follower.example.test".to_string(),
            access_key: "plain-access-key".to_string(),
            secret_key: "plain-secret-key".to_string(),
            is_enabled: true,
            transport_mode: RemoteNodeTransportMode::Direct,
            last_capabilities: "{}".to_string(),
            last_error: String::new(),
            last_checked_at: None,
            tunnel_last_error: String::new(),
            binding_revision: 1,
            binding_applied_revision: 0,
            tunnel_last_seen_at: None,
            created_at: now,
            updated_at: now,
        };

        let debug = format!("{model:?}");
        assert!(debug.contains(r#"access_key: "***REDACTED***""#));
        assert!(debug.contains(r#"secret_key: "***REDACTED***""#));
        assert!(!debug.contains("plain-access-key"));
        assert!(!debug.contains("plain-secret-key"));
    }
}
